import { useState, useRef, useEffect } from "react";

// ─── AkiliYaBiashara ──────────────────────────────────────────────────────────
// The selling point. An AI business advisor that speaks like a trusted friend,
// not a dashboard. Watches shop data 24/7 and surfaces plain-language insights
// in Swahili and English. Powered by your AI backend.
//
// SELLING PITCH TO OWNER:
// "Hii si programu tu. Ni mshauri wa biashara anayejua duka lako vyema kuliko wewe."
// "This isn't just software. It's a business advisor who knows your shop better than you do."
//
// THREE MODES:
//   1. Daily Insights Feed — proactive AI-generated observations from shop data
//   2. Ask Akili — freeform chat with context of entire business history
//   3. Predictions — what will happen this week based on patterns
//
// Props:
//   shopData  — live business data object
//   apiKey    — your Anthropic API key (handled server-side in production)
//   theme     — "dark" | "light"

const BRAND = "#E56B0A";
const AKILI_COLOR = "#7c3aed"; // Purple — distinct from brand orange, feels "intelligent"

const fmt = n => "TSh " + Number(n).toLocaleString("en-TZ");

// ── Sample shop context (replace with live data from your state) ──────────────
const SAMPLE_SHOP = {
  name: "Duka la Mwanga",
  owner: "Amina",
  weekRevenue: 1284000,
  weekTransactions: 218,
  weekExpenses: 312000,
  weekProfit: 972000,
  topProducts: [
    { name: "Unga wa Sembe 2kg", unitsSold: 124, revenue: 434000, stock: 3, reorderThreshold: 10 },
    { name: "Mafuta ya Kupikia 1L", unitsSold: 67, revenue: 281400, stock: 1, reorderThreshold: 5 },
    { name: "Sukari 1kg", unitsSold: 89, revenue: 249200, stock: 8, reorderThreshold: 12 },
  ],
  overdueDebt: 189500,
  debtors: 6,
  bestHour: "09:00–11:00",
  bestDay: "Saturday",
  worstDay: "Monday",
  peakSaturday: 287000,
  avgDailySales: 183000,
  paymentSplit: { mpesa: 58, cash: 31, airtel: 11 },
  staffCount: 3,
  monthsActive: 5,
  creditScore: 68,
  stockoutsThisWeek: 3,
};

// ── Pre-built proactive insights (in production: generated by AI from live data) ─
const DAILY_INSIGHTS = [
  {
    id: 1,
    type: "money",
    urgency: "high",
    emoji: "💡",
    title: "Unaficha faida yako kwenye duka la dawa",
    titleEn: "You're hiding profit in your stock timing",
    body: "Unamaliza Unga wa Sembe asubuhi ya Jumamosi — saa 4 kabla ya kufunga. Unakosa mauzo ya TSh 28,000 kila wiki moja kwa moja. Agiza kila siku ya Ijumaa, si Jumatatu.",
    bodyEn: "You run out of Unga wa Sembe on Saturday mornings — 4 hours before close. You're missing TSh 28,000 in sales every single week. Order every Friday, not Monday.",
    impact: "+TSh 28,000/week",
    actionLabel: "Order Unga Now",
    actionColor: "#22c55e",
    category: "Stock",
  },
  {
    id: 2,
    type: "warning",
    urgency: "high",
    emoji: "⚠️",
    title: "Deni lako linakula faida yako",
    titleEn: "Your debt book is eating your profit",
    body: "Wateja 6 wanakudai TSh 189,500. Hii ni sawa na siku 2 za mauzo yako. Fatuma Salim amekaa siku 14 — tuma ujumbe sasa.",
    bodyEn: "6 customers owe you TSh 189,500. That's 2 days of your sales sitting in their pockets. Fatuma Salim is 14 days overdue — send a message now.",
    impact: "TSh 189,500 at risk",
    actionLabel: "Chase Debts",
    actionColor: "#ef4444",
    category: "Debt",
  },
  {
    id: 3,
    type: "growth",
    urgency: "medium",
    emoji: "📈",
    title: "Jumamosi yako ni duka lingine kabisa",
    titleEn: "Your Saturday is basically a different shop",
    body: "Jumamosi unauza TSh 287,000 — sawa na mara mbili ya siku nyingine. Lakini una wafanyakazi wawili tu. Ongeza mtu mmoja Jumamosi asubuhi — utaongeza mauzo ya TSh 40,000.",
    bodyEn: "Saturday you sell TSh 287,000 — nearly double any other day. But you only have 2 staff. Add one person Saturday mornings — you'll capture TSh 40,000 more.",
    impact: "+TSh 40,000/Saturday",
    actionLabel: "Schedule Staff",
    actionColor: BRAND,
    category: "Staff",
  },
  {
    id: 4,
    type: "insight",
    urgency: "medium",
    emoji: "🎯",
    title: "Wateja wako wanalipia kwa M-Pesa zaidi",
    titleEn: "Your customers are shifting to M-Pesa",
    body: "M-Pesa sasa ni 58% ya malipo — ilikuwa 44% miezi 3 iliyopita. Hii inamaanisha unaweza kuomba mkopo wa Pesapal (inahitaji 60%). Uko karibu sana.",
    bodyEn: "M-Pesa is now 58% of payments — it was 44% three months ago. This means you're almost eligible for a Pesapal Credit loan (requires 60% digital). You're very close.",
    impact: "2% from loan eligibility",
    actionLabel: "Check Eligibility",
    actionColor: AKILI_COLOR,
    category: "Finance",
  },
  {
    id: 5,
    type: "pattern",
    urgency: "low",
    emoji: "🔍",
    title: "Wateja wako wanunua zaidi saa 9–11 asubuhi",
    titleEn: "Your peak hour is 9–11am, not noon",
    body: "Wateja wengi wanakuja saa 3–5 asubuhi (9–11am). Lakini wewe hujawa dukani — Juma ndiye anayemaliza mauzo yako ya asubuhi. Wewe uko saa ngapi nyumbani?",
    bodyEn: "Most customers come 9–11am. But you're often not there — Juma handles your peak hours. Are you capturing every sale that could happen with you present?",
    impact: "Unknown lost sales",
    actionLabel: "Review Clock Logs",
    actionColor: "#3b82f6",
    category: "Operations",
  },
];

const PREDICTIONS = [
  { day: "Jumatano", dayEn: "Wednesday", predicted: 165000, confidence: 87, note: "Kawaida ya wiki hii" },
  { day: "Alhamisi", dayEn: "Thursday", predicted: 172000, confidence: 82, note: "Kidogo juu ya wastani" },
  { day: "Ijumaa", dayEn: "Friday", predicted: 198000, confidence: 79, note: "Mwisho wa wiki — wateja wengi" },
  { day: "Jumamosi", dayEn: "Saturday", predicted: 291000, confidence: 91, note: "Siku yako bora — kuwa tayari" },
  { day: "Jumapili", dayEn: "Sunday", predicted: 134000, confidence: 74, note: "Kidogo — pumzika kidogo" },
  { day: "Jumatatu", dayEn: "Monday", predicted: 108000, confidence: 85, note: "Siku yako ngumu zaidi" },
  { day: "Jumanne", dayEn: "Tuesday", predicted: 151000, confidence: 80, note: "Wastani wa kawaida" },
];

const css = `
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap');

.akili-root{font-family:'Plus Jakarta Sans',sans-serif;width:100%}
.akili-root.dark{--bg:#0f1117;--card:#1a1d27;--inp:#22263a;--border:#2e3347;--t:#f0f2ff;--t2:#7c85a8;--t3:#4a5170;--akili-bg:#160e2a;--akili-border:rgba(124,58,237,.25);--msg-bg:#1e1433}
.akili-root.light{--bg:#f4f5f9;--card:#fff;--inp:#f8f9fc;--border:#e2e5ef;--t:#1a1d2e;--t2:#5b6380;--t3:#9ba3bf;--akili-bg:#f5f3ff;--akili-border:rgba(124,58,237,.15);--msg-bg:#ede9fe}

.akili-hero{background:var(--akili-bg);border:1px solid var(--akili-border);border-radius:20px;padding:20px;margin-bottom:16px;position:relative;overflow:hidden}
.akili-hero::before{content:'';position:absolute;top:0;right:0;width:120px;height:120px;background:radial-gradient(circle,rgba(124,58,237,.12) 0%,transparent 70%);border-radius:50%}
.akili-avatar{width:52px;height:52px;border-radius:50%;background:linear-gradient(135deg,${AKILI_COLOR},#5b21b6);display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0;position:relative}
.akili-avatar::after{content:'';position:absolute;bottom:0;right:0;width:14px;height:14px;border-radius:50%;background:#22c55e;border:2px solid var(--akili-bg)}
.akili-pulse{animation:akili-pulse 2s ease-in-out infinite}
@keyframes akili-pulse{0%,100%{opacity:1}50%{opacity:.6}}

.akili-tabs{display:flex;gap:4px;background:var(--inp);border-radius:12px;padding:3px;margin-bottom:16px}
.akili-tab{flex:1;padding:8px 6px;border-radius:9px;font-size:11px;font-weight:700;cursor:pointer;border:none;font-family:inherit;background:transparent;color:var(--t2);transition:all .15s;text-align:center}
.akili-tab.active{background:${AKILI_COLOR};color:#fff}

.insight-card{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:15px;margin-bottom:10px;transition:border-color .15s;cursor:pointer}
.insight-card:hover{border-color:rgba(124,58,237,.4)}
.insight-card.high{border-left:3px solid #ef4444;border-radius:0 14px 14px 0}
.insight-card.medium{border-left:3px solid ${BRAND};border-radius:0 14px 14px 0}
.insight-card.low{border-left:3px solid #3b82f6;border-radius:0 14px 14px 0}
.insight-top{display:flex;align-items:flex-start;gap:10px}
.insight-emoji{font-size:20px;flex-shrink:0;margin-top:1px}
.insight-title{font-size:13px;font-weight:800;color:var(--t);line-height:1.3}
.insight-title-sw{font-size:11px;font-weight:600;color:var(--t2);margin-top:2px;font-style:italic}
.insight-body{font-size:12px;color:var(--t2);line-height:1.6;margin-top:8px}
.insight-body-sw{font-size:11px;color:var(--t2);line-height:1.5;margin-top:4px;padding-top:6px;border-top:1px dashed var(--border)}
.insight-footer{display:flex;align-items:center;justify-content:space-between;margin-top:10px}
.impact-badge{font-size:10px;font-weight:800;padding:3px 10px;border-radius:20px;border:1px solid}
.insight-action-btn{font-size:11px;font-weight:700;padding:6px 14px;border-radius:8px;border:none;cursor:pointer;font-family:inherit;color:#fff;transition:all .15s}
.insight-action-btn:hover{opacity:.9;transform:translateY(-1px)}
.cat-badge{font-size:9px;font-weight:700;padding:2px 8px;border-radius:8px;background:var(--inp);color:var(--t2);margin-left:6px}

.chat-container{background:var(--card);border:1px solid var(--border);border-radius:16px;overflow:hidden}
.chat-messages{padding:16px;min-height:300px;max-height:400px;overflow-y:auto;display:flex;flex-direction:column;gap:12px;scrollbar-width:thin;scrollbar-color:var(--border) transparent}
.msg{display:flex;gap:10px;animation:msgIn .2s ease}
@keyframes msgIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
.msg.user{flex-direction:row-reverse}
.msg-avatar{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:800;flex-shrink:0;align-self:flex-end}
.msg-bubble{max-width:80%;padding:10px 14px;border-radius:14px;font-size:13px;line-height:1.5}
.msg.akili .msg-bubble{background:var(--msg-bg);color:var(--t);border-radius:4px 14px 14px 14px}
.msg.user .msg-bubble{background:${AKILI_COLOR};color:#fff;border-radius:14px 14px 4px 14px}
.msg-time{font-size:10px;color:var(--t3);margin-top:4px}
.typing{display:flex;gap:4px;padding:10px 14px;background:var(--msg-bg);border-radius:4px 14px 14px 14px;width:fit-content}
.typing-dot{width:6px;height:6px;border-radius:50%;background:${AKILI_COLOR};animation:typing .8s ease-in-out infinite}
.typing-dot:nth-child(2){animation-delay:.15s}
.typing-dot:nth-child(3){animation-delay:.3s}
@keyframes typing{0%,80%,100%{transform:scale(1);opacity:.5}40%{transform:scale(1.2);opacity:1}}

.chat-input-row{padding:12px 14px;border-top:1px solid var(--border);display:flex;gap:8px;align-items:center}
.chat-input{flex:1;background:var(--inp);border:1.5px solid var(--border);border-radius:10px;padding:10px 13px;font-size:13px;color:var(--t);font-family:inherit;outline:none;transition:border-color .15s;resize:none}
.chat-input:focus{border-color:${AKILI_COLOR}}
.chat-send-btn{width:38px;height:38px;border-radius:10px;background:${AKILI_COLOR};color:#fff;border:none;cursor:pointer;font-size:16px;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:background .15s}
.chat-send-btn:hover{background:#6d28d9}
.chat-send-btn:disabled{opacity:.4;cursor:not-allowed}
.quick-prompts{padding:8px 14px 0;display:flex;gap:6px;flex-wrap:wrap}
.quick-btn{background:var(--inp);border:1px solid var(--border);color:var(--t2);border-radius:20px;padding:5px 12px;font-size:11px;font-weight:600;cursor:pointer;font-family:inherit;transition:all .15s}
.quick-btn:hover{border-color:${AKILI_COLOR};color:${AKILI_COLOR}}

.pred-row{background:var(--card);border:1px solid var(--border);border-radius:11px;padding:12px 14px;margin-bottom:7px;display:flex;align-items:center;gap:12px}
.pred-day{font-size:12px;font-weight:700;color:var(--t);min-width:75px}
.pred-day-sw{font-size:10px;color:var(--t2);font-style:italic}
.pred-bar-wrap{flex:1}
.pred-bar-track{height:8px;background:var(--border);border-radius:4px;overflow:hidden}
.pred-bar-fill{height:100%;border-radius:4px;transition:width .5s}
.pred-note{font-size:10px;color:var(--t2);margin-top:3px}
.pred-amount{font-size:12px;font-weight:800;color:var(--t);text-align:right;min-width:80px;flex-shrink:0}
.pred-conf{font-size:9px;color:var(--t2);text-align:right}
.confidence-ring{width:32px;height:32px;flex-shrink:0}

.lang-toggle{display:flex;background:var(--inp);border-radius:8px;overflow:hidden;margin-bottom:14px;width:fit-content}
.lang-btn{padding:5px 14px;font-size:11px;font-weight:700;border:none;cursor:pointer;font-family:inherit;background:transparent;color:var(--t2);transition:all .15s}
.lang-btn.active{background:${AKILI_COLOR};color:#fff}
`;

// ── System prompt for Akili (used when calling Anthropic API in production) ──
export const AKILI_SYSTEM_PROMPT = (shopData) => `
You are Akili, an AI business advisor for ${shopData.name} in Dar es Salaam, Tanzania.
You are like a brilliant, trusted older sibling who happens to be a business expert.
You speak directly, warmly, and practically — never corporate, never condescending.

CRITICAL RULES:
- Always answer in BOTH Swahili and English (Swahili first, then English below it)
- Use the owner's name: ${shopData.owner}
- Speak like a friend who knows their shop intimately, not a dashboard
- Give specific numbers from their data, not generalisations  
- Every answer should end with ONE clear action, not a list of options
- Keep responses short — max 4 sentences in each language
- Never say "based on your data" — just say what you see
- Use TSh for currency, always

SHOP DATA YOU KNOW:
- Weekly revenue: ${fmt(shopData.weekRevenue)} 
- Weekly profit: ${fmt(shopData.weekProfit)} (${Math.round((shopData.weekProfit/shopData.weekRevenue)*100)}% margin)
- Top seller: ${shopData.topProducts[0]?.name} (${shopData.topProducts[0]?.unitsSold} units this week)
- ${shopData.topProducts[0]?.name} stock: ${shopData.topProducts[0]?.stock} units left (threshold: ${shopData.topProducts[0]?.reorderThreshold})
- Overdue debt: ${fmt(shopData.overdueDebt)} across ${shopData.debtors} customers
- Best hour: ${shopData.bestHour}
- Best day: ${shopData.bestDay} (${fmt(shopData.peakSaturday)})
- Worst day: ${shopData.worstDay}
- Payment: ${shopData.paymentSplit.mpesa}% M-Pesa, ${shopData.paymentSplit.cash}% Cash
- Staff: ${shopData.staffCount} people
- Credit score: ${shopData.creditScore}/100
- Stockouts this week: ${shopData.stockoutsThisWeek}

TONE EXAMPLES:
Good: "Amina, unamaliza Unga saa 4 kabla ya kufunga Jumamosi — unakosa TSh 28K kila wiki. Agiza Ijumaa."
Bad: "Based on your inventory data, I recommend optimising your reorder schedule."
`;

const INITIAL_MESSAGES = [
  {
    role: "akili",
    content: "Habari Amina! Nimekagua duka lako leo. Kuna kitu kimoja muhimu sana unachohitaji kujua — Unga wako utaisha Jumamosi asubuhi tena. Hii ni mara ya 3 mfululizo. 📦\n\nHi Amina! I've been watching your shop. There's one thing you urgently need to know — your Unga will run out Saturday morning again. Third week in a row.",
    time: "Just now",
  },
];

const QUICK_PROMPTS_EN = [
  "Why is Monday always slow?",
  "Am I making real profit?",
  "Who owes me the most?",
  "Should I hire more staff?",
  "What should I stock more of?",
  "Can I get a loan?",
];

const QUICK_PROMPTS_SW = [
  "Kwa nini Jumatatu ni polepole?",
  "Je, ninafanya faida halisi?",
  "Nani ananidai zaidi?",
  "Niongeze wafanyakazi?",
  "Niongeze bidhaa gani?",
  "Naweza kupata mkopo?",
];

export default function AkiliYaBiashara({ shopData = SAMPLE_SHOP, theme = "dark" }) {
  const [tab, setTab] = useState("insights");
  const [lang, setLang] = useState("both");
  const [messages, setMessages] = useState(INITIAL_MESSAGES);
  const [inputVal, setInputVal] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [expandedInsight, setExpandedInsight] = useState(null);
  const chatEndRef = useRef(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  const sendMessage = async (text) => {
    if (!text.trim() || isTyping) return;
    const userMsg = { role: "user", content: text, time: new Date().toLocaleTimeString("en-TZ", { hour: "2-digit", minute: "2-digit" }) };
    setMessages(prev => [...prev, userMsg]);
    setInputVal("");
    setIsTyping(true);

    // In production: replace with real Anthropic API call
    // const response = await fetch("https://api.anthropic.com/v1/messages", {
    //   method: "POST",
    //   headers: { "Content-Type": "application/json" },
    //   body: JSON.stringify({
    //     model: "claude-sonnet-4-20250514",
    //     max_tokens: 400,
    //     system: AKILI_SYSTEM_PROMPT(shopData),
    //     messages: [{ role: "user", content: text }]
    //   })
    // });

    // Simulated responses keyed to common questions
    const responses = {
      "monday": "Jumatatu ni polepole kwa sababu wateja wanamaliza pesa za mwisho wa wiki Jumapili. Wastani wako ni TSh 108,000 tu — nusu ya Alhamisi. Tumia Jumatatu kupanga hisa na kusafisha — si siku ya kutegemea mauzo.\n\nMonday is slow because customers spent their weekend money on Sunday. Your average is just TSh 108,000 — half of Thursday. Use Monday for stock planning and cleaning, not sales.",
      "profit": `Ndio — lakini si kama unavyofikiri. Unapata TSh ${Math.round(shopData.weekProfit/1000)}K kwa wiki — ${Math.round((shopData.weekProfit/shopData.weekRevenue)*100)}% margin. Hii ni nzuri. Tatizo ni wateja 6 wanaokudai ${fmt(shopData.overdueDebt)} — hii inabeba kama hasara.\n\nYes — but not as much as you think. You're netting TSh ${Math.round(shopData.weekProfit/1000)}K/week at ${Math.round((shopData.weekProfit/shopData.weekRevenue)*100)}% margin. That's solid. The problem is 6 customers holding ${fmt(shopData.overdueDebt)} of your money.`,
      "owes": "Fatuma Salim ndiye mkubwa — amekaa siku 14. Kisha Juma Ally na Hassan Mwenda. Jumla TSh 189,500. Tuma ujumbe WhatsApp sasa hivi, asubuhi, sio jioni — uwezekano wa kulipwa ni mara mbili zaidi.\n\nFatuma Salim is your biggest — 14 days overdue. Then Juma Ally and Hassan Mwenda. Total TSh 189,500. Send WhatsApp messages this morning, not evening — twice as likely to get paid.",
      "staff": "Wafanyakazi wako 3 ni wa kutosha wiki nzima isipokuwa Jumamosi. Unakosa mtu mmoja saa 3–7 asubuhi (9–11am). Hilo ni saa zako za kilele. Ongeza mtu mmoja tu Jumamosi asubuhi — utaongeza TSh 40,000 kwa wiki.\n\nYour 3 staff are enough for the whole week except Saturday morning. You need one more person 9–11am on Saturdays. That's your peak. Add just one person Saturday morning — you'll capture TSh 40,000 more per week.",
      "loan": `Alama yako ya mkopo ni ${shopData.creditScore}/100. Unahitaji 65+ kwa Pesapal na 70+ kwa NMB. Uko karibu. Kitu kimoja kitakusaidia haraka: kukusanya deni lako la TSh 189,500 — kinaonyesha unaweza kusimamia fedha.\n\nYour credit score is ${shopData.creditScore}/100. You need 65+ for Pesapal and 70+ for NMB. You're close. The one thing that'll help fastest: collecting your TSh 189,500 debt — it shows you can manage money.`,
      "default": "Ninaona mauzo yako yanakwenda vizuri wiki hii. Jambo moja muhimu: hakikisha una Unga wa kutosha Ijumaa jioni — unamaliza kila Jumamosi asubuhi. Hiyo inakugharimu TSh 28,000 kila wiki.\n\nI can see your sales are going well this week. One critical thing: make sure you have enough Unga by Friday evening — you run out every Saturday morning. That's costing you TSh 28,000 every single week.",
    };

    const lower = text.toLowerCase();
    let reply = responses.default;
    if (lower.includes("monday") || lower.includes("jumatatu") || lower.includes("slow") || lower.includes("polepole")) reply = responses.monday;
    else if (lower.includes("profit") || lower.includes("faida") || lower.includes("making money")) reply = responses.profit;
    else if (lower.includes("owes") || lower.includes("owes") || lower.includes("loan") || lower.includes("mkopo")) reply = responses.loan;
    else if (lower.includes("staff") || lower.includes("wafanyakazi") || lower.includes("hire")) reply = responses.staff;
    else if (lower.includes("who") || lower.includes("nani") || lower.includes("debt") || lower.includes("deni")) reply = responses.owes;

    setTimeout(() => {
      setIsTyping(false);
      setMessages(prev => [...prev, {
        role: "akili",
        content: reply,
        time: new Date().toLocaleTimeString("en-TZ", { hour: "2-digit", minute: "2-digit" }),
      }]);
    }, 1800);
  };

  const maxPred = Math.max(...PREDICTIONS.map(p => p.predicted));

  return (
    <>
      <style>{css}</style>
      <div className={`akili-root ${theme}`}>
        {/* Hero */}
        <div className="akili-hero">
          <div style={{ display: "flex", alignItems: "center", gap: 14, position: "relative" }}>
            <div className="akili-avatar">🧠</div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: "rgba(124,58,237,.7)", textTransform: "uppercase", letterSpacing: ".8px", marginBottom: 3 }}>
                Akili ya Biashara · Business Intelligence
              </div>
              <div style={{ fontSize: 16, fontWeight: 800, color: "var(--t)" }}>
                Habari, {shopData.owner}!
              </div>
              <div style={{ fontSize: 11, color: "var(--t2)", marginTop: 2 }}>
                Nina uchanganuzi {DAILY_INSIGHTS.length} mpya leo · I have {DAILY_INSIGHTS.length} new insights for you
              </div>
            </div>
            <div style={{ textAlign: "right", flexShrink: 0 }}>
              <div style={{ fontSize: 9, fontWeight: 700, color: "rgba(124,58,237,.6)", textTransform: "uppercase", marginBottom: 4 }}>
                Week Revenue
              </div>
              <div style={{ fontSize: 16, fontWeight: 800, color: "var(--t)" }}>
                {fmt(shopData.weekRevenue)}
              </div>
              <div style={{ fontSize: 10, color: "#22c55e", fontWeight: 700, marginTop: 2 }}>
                ↑ 16% vs last week
              </div>
            </div>
          </div>
          {/* Quick stat pills */}
          <div style={{ display: "flex", gap: 6, marginTop: 14, flexWrap: "wrap" }}>
            {[
              { label: "Profit", value: `${Math.round((shopData.weekProfit/shopData.weekRevenue)*100)}%`, color: "#22c55e" },
              { label: "Debt at risk", value: fmt(shopData.overdueDebt), color: "#ef4444" },
              { label: "Stockouts", value: shopData.stockoutsThisWeek, color: "#f59e0b" },
              { label: "Credit score", value: shopData.creditScore+"/100", color: AKILI_COLOR },
            ].map(s => (
              <div key={s.label} style={{ background: "rgba(255,255,255,.06)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, padding: "5px 10px" }}>
                <div style={{ fontSize: 8, color: "rgba(255,255,255,.4)", fontWeight: 700, textTransform: "uppercase", letterSpacing: ".4px" }}>{s.label}</div>
                <div style={{ fontSize: 11, fontWeight: 800, color: s.color, marginTop: 1 }}>{s.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Language toggle */}
        <div className="lang-toggle">
          {[["both","SW + EN"],["sw","Swahili"],["en","English"]].map(([k,l]) => (
            <button key={k} className={`lang-btn ${lang===k?"active":""}`} onClick={() => setLang(k)}>{l}</button>
          ))}
        </div>

        {/* Tabs */}
        <div className="akili-tabs">
          <button className={`akili-tab ${tab==="insights"?"active":""}`} onClick={() => setTab("insights")}>
            💡 Insights
          </button>
          <button className={`akili-tab ${tab==="chat"?"active":""}`} onClick={() => setTab("chat")}>
            💬 Ask Akili
          </button>
          <button className={`akili-tab ${tab==="predict"?"active":""}`} onClick={() => setTab("predict")}>
            🔮 Predictions
          </button>
        </div>

        {/* ── INSIGHTS ── */}
        {tab === "insights" && (
          <>
            {DAILY_INSIGHTS.map(insight => {
              const isExpanded = expandedInsight === insight.id;
              return (
                <div key={insight.id}
                  className={`insight-card ${insight.urgency}`}
                  onClick={() => setExpandedInsight(isExpanded ? null : insight.id)}>
                  <div className="insight-top">
                    <span className="insight-emoji" style={{ fontSize: 20 }}>{insight.emoji}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: "flex", alignItems: "center" }}>
                        <span className="insight-title">
                          {lang === "sw" ? insight.title : lang === "en" ? insight.titleEn : insight.titleEn}
                        </span>
                        <span className="cat-badge">{insight.category}</span>
                      </div>
                      {(lang === "both" || lang === "sw") && (
                        <div className="insight-title-sw">{insight.title}</div>
                      )}
                    </div>
                  </div>

                  {isExpanded && (
                    <>
                      {(lang === "en" || lang === "both") && (
                        <div className="insight-body">{insight.bodyEn}</div>
                      )}
                      {lang === "both" && (
                        <div className="insight-body-sw">{insight.body}</div>
                      )}
                      {lang === "sw" && (
                        <div className="insight-body">{insight.body}</div>
                      )}
                    </>
                  )}

                  <div className="insight-footer">
                    <span className="impact-badge"
                      style={{ background: `${insight.actionColor}12`, borderColor: `${insight.actionColor}25`, color: insight.actionColor }}>
                      {insight.impact}
                    </span>
                    <button
                      className="insight-action-btn"
                      style={{ background: insight.actionColor }}
                      onClick={e => { e.stopPropagation(); }}>
                      {insight.actionLabel}
                    </button>
                  </div>
                </div>
              );
            })}
          </>
        )}

        {/* ── CHAT ── */}
        {tab === "chat" && (
          <div className="chat-container">
            {/* Quick prompts */}
            <div className="quick-prompts">
              {(lang === "sw" ? QUICK_PROMPTS_SW : QUICK_PROMPTS_EN).map(q => (
                <button key={q} className="quick-btn" onClick={() => sendMessage(q)}>{q}</button>
              ))}
            </div>

            {/* Messages */}
            <div className="chat-messages">
              {messages.map((msg, i) => (
                <div key={i} className={`msg ${msg.role}`}>
                  <div className="msg-avatar"
                    style={{ background: msg.role === "akili" ? `linear-gradient(135deg,${AKILI_COLOR},#5b21b6)` : BRAND, color: "#fff" }}>
                    {msg.role === "akili" ? "🧠" : shopData.owner[0]}
                  </div>
                  <div>
                    <div className="msg-bubble"
                      style={{ whiteSpace: "pre-line" }}>
                      {msg.content}
                    </div>
                    <div className="msg-time" style={{ textAlign: msg.role === "user" ? "right" : "left" }}>
                      {msg.role === "akili" ? "Akili · " : ""}{msg.time}
                    </div>
                  </div>
                </div>
              ))}
              {isTyping && (
                <div className="msg akili">
                  <div className="msg-avatar" style={{ background: `linear-gradient(135deg,${AKILI_COLOR},#5b21b6)`, color: "#fff" }}>🧠</div>
                  <div className="typing">
                    <div className="typing-dot" />
                    <div className="typing-dot" />
                    <div className="typing-dot" />
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Input */}
            <div className="chat-input-row">
              <textarea
                className="chat-input"
                rows={1}
                placeholder={lang === "sw" ? "Uliza Akili swali lolote..." : "Ask Akili anything about your shop..."}
                value={inputVal}
                onChange={e => setInputVal(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(inputVal); }}}
              />
              <button className="chat-send-btn" onClick={() => sendMessage(inputVal)} disabled={!inputVal.trim() || isTyping}>
                →
              </button>
            </div>
          </div>
        )}

        {/* ── PREDICTIONS ── */}
        {tab === "predict" && (
          <>
            <div style={{ background: "var(--akili-bg)", border: "1px solid var(--akili-border)", borderRadius: 12, padding: "12px 14px", marginBottom: 14, fontSize: 12, color: "var(--t2)", lineHeight: 1.6 }}>
              🔮 {lang === "sw"
                ? "Hizi ni utabiri wa mauzo yako kulingana na miaka 5 ya takwimu za soko na historia yako ya wiki 20."
                : "These predictions are based on 5 years of Dar es Salaam market patterns combined with your 20-week sales history."}
            </div>
            {PREDICTIONS.map(pred => {
              const pct = Math.round((pred.predicted / maxPred) * 100);
              const barColor = pred.predicted >= 250000 ? "#22c55e" : pred.predicted >= 160000 ? BRAND : pred.predicted >= 130000 ? "#f59e0b" : "#ef4444";
              return (
                <div key={pred.day} className="pred-row">
                  <div>
                    <div className="pred-day">{lang === "sw" ? pred.day : pred.dayEn}</div>
                    {lang === "both" && <div className="pred-day-sw">{pred.day}</div>}
                  </div>
                  <div className="pred-bar-wrap">
                    <div className="pred-bar-track">
                      <div className="pred-bar-fill" style={{ width: `${pct}%`, background: barColor }} />
                    </div>
                    <div className="pred-note">{lang === "sw" ? pred.note : pred.note}</div>
                  </div>
                  <div>
                    <div className="pred-amount">{fmt(pred.predicted)}</div>
                    <div className="pred-conf">{pred.confidence}% confident</div>
                  </div>
                </div>
              );
            })}
            <div style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 12, padding: "12px 14px", marginTop: 4, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: "var(--t)" }}>
                  {lang === "sw" ? "Jumla ya wiki ijayo" : "Projected week total"}
                </div>
                <div style={{ fontSize: 10, color: "var(--t2)", marginTop: 2 }}>
                  {lang === "sw" ? "Ikiwa utafuata mapendekezo yote" : "If you follow all recommendations"}
                </div>
              </div>
              <div style={{ textAlign: "right" }}>
                <div style={{ fontSize: 18, fontWeight: 800, color: "#22c55e" }}>
                  {fmt(PREDICTIONS.reduce((s, p) => s + p.predicted, 0))}
                </div>
                <div style={{ fontSize: 10, color: "#22c55e", marginTop: 2 }}>
                  +TSh 87,000 vs this week
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
}
