import { useState } from "react";

const BRAND = "#E56B0A";
const fmt = (n, currency = "KSh") => currency + " " + Number(n).toLocaleString("en-KE");
const fmtTZ = n => "TSh " + Number(n).toLocaleString("en-TZ");

// ─── KRAeTIMSInvoice ──────────────────────────────────────────────────────────
// Spec: "KRA eTIMS-Compliant Invoicing: Real-time invoice transmission to KRA
//        with QR codes, buyer/seller PINs, mandatory fields."
// Kenya eTIMS mandate: all businesses must issue electronic tax invoices (Sept 2023)
//
// KRA certification process: 3-6 months (see spec section E)
// API: KRA eTIMS device/VSCU (Virtual Sales Control Unit) integration
// Docs: itax.kra.go.ke/KRA-Portal/
//
// Required fields per KRA eTIMS spec:
// - Seller PIN, Name, Address
// - Buyer PIN (if VAT-registered), Name
// - Invoice Number (sequential, per eTIMS device)
// - Invoice Date & Time
// - Item description, quantity, unit price
// - VAT rate (16% standard) and amount
// - Total excl. VAT, VAT amount, Total incl. VAT
// - QR code (generated by KRA VSCU containing verification data)
// - eTIMS confirmation code from KRA

const SAMPLE_ETIMS = {
  invoiceNo: "ETM-2025-00341",
  sellerPIN: "P051234567A",
  sellerName: "Duka la Mwanga Ltd",
  sellerAddress: "Westlands, Nairobi",
  buyerPIN: "P059876543B",
  buyerName: "Karibu Restaurant Ltd",
  date: "2025-03-14",
  time: "14:23:07",
  items: [
    { desc: "Cooking Oil 5L", qty: 10, unitPrice: 850, vatRate: 0.16 },
    { desc: "Sugar 50kg Bag", qty: 5, unitPrice: 4200, vatRate: 0.16 },
    { desc: "Unga wa Sembe 10kg", qty: 8, unitPrice: 1200, vatRate: 0 },
  ],
  kraConfirmCode: "KRA-ETMS-20250314-982341",
  transmitted: true,
};

export function KRAeTIMSInvoice({ theme = "dark", data = SAMPLE_ETIMS }) {
  const [sending, setSending] = useState(false);
  const [confirmed, setConfirmed] = useState(data.transmitted);
  const [activeTab, setActiveTab] = useState("invoice");

  const subtotalExVAT = data.items.reduce((s, i) => s + i.qty * i.unitPrice, 0);
  const vatTotal = data.items.reduce((s, i) => s + Math.round(i.qty * i.unitPrice * i.vatRate), 0);
  const grandTotal = subtotalExVAT + vatTotal;
  const vatableItems = data.items.filter(i => i.vatRate > 0);
  const exemptItems  = data.items.filter(i => i.vatRate === 0);

  const transmit = () => {
    setSending(true);
    setTimeout(() => { setSending(false); setConfirmed(true); }, 2200);
  };

  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap');
    .et-root{font-family:'Plus Jakarta Sans',sans-serif}
    .et-root.dark{--card:#1a1d27;--inp:#22263a;--border:#2e3347;--t:#f0f2ff;--t2:#7c85a8;--t3:#4a5170}
    .et-root.light{--card:#fff;--inp:#f8f9fc;--border:#e2e5ef;--t:#1a1d2e;--t2:#5b6380;--t3:#9ba3bf}
    .et-tabs{display:flex;gap:3px;background:var(--inp);border-radius:10px;padding:3px;margin-bottom:14px}
    .et-tab{flex:1;padding:7px;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer;border:none;font-family:inherit;background:transparent;color:var(--t2);transition:all .15s;text-align:center}
    .et-tab.active{background:${BRAND};color:#fff}
    .et-receipt{background:var(--inp);border:1px solid var(--border);border-radius:12px;padding:18px;font-family:'IBM Plex Mono',monospace;font-size:11px;line-height:1.9}
    .et-r{display:flex;justify-content:space-between;color:var(--t2)}
    .et-div{border:none;border-top:1px dashed var(--border);margin:7px 0}
    .et-total{display:flex;justify-content:space-between;font-family:'Plus Jakarta Sans',sans-serif;font-size:13px;font-weight:800;color:var(--t)}
    .et-qr{width:80px;height:80px;border:3px solid var(--border);border-radius:8px;display:flex;align-items:center;justify-content:center;margin:10px auto;position:relative;background:var(--card)}
    .et-qr-inner{width:60px;height:60px;display:grid;grid-template-columns:repeat(8,1fr);gap:1px}
    .et-qr-cell{border-radius:1px}
    .et-btn{background:${BRAND};color:#fff;border:none;border-radius:9px;padding:10px 18px;font-size:13px;font-weight:700;cursor:pointer;font-family:inherit;transition:all .15s}
    .et-btn.grn{background:#22c55e}
    .et-kenya-flag{width:20px;height:14px;display:inline-block;vertical-align:middle;margin-right:6px;overflow:hidden;border-radius:2px}
    .et-field{margin-bottom:10px}
    .et-lbl{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.7px;color:${BRAND};margin-bottom:4px;display:block}
    .et-inp{width:100%;background:var(--inp);border:1.5px solid var(--border);border-radius:8px;padding:8px 11px;font-size:12px;color:var(--t);font-family:inherit;outline:none;transition:border-color .15s;box-sizing:border-box}
    .et-inp:focus{border-color:${BRAND}}
    .et-r2{display:grid;grid-template-columns:1fr 1fr;gap:10px}
  `;

  // Simple QR-like pattern
  const QR_PATTERN = Array.from({length:64}, (_,i) => {
    const row = Math.floor(i/8), col = i%8;
    return ((row+col) % 3 === 0 || (row*col) % 5 === 0 || row < 2 || col < 2 || row > 5 || col > 5);
  });

  return (
    <>
      <style>{css}</style>
      <div className={`et-root ${theme}`}>
        <div style={{ marginBottom:14 }}>
          <div style={{ fontSize:18, fontWeight:800, color:"var(--t)" }}>
            KRA <span style={{ color:BRAND }}>eTIMS</span> Invoice
          </div>
          <div style={{ fontSize:11, color:"var(--t2)", marginTop:2, display:"flex", alignItems:"center", gap:6 }}>
            <span>Kenya Electronic Tax Invoice · VAT 16% · Mandatory Sept 2023</span>
            <span style={{ fontSize:9, fontWeight:700, padding:"2px 8px", borderRadius:20,
              background: confirmed ? "rgba(34,197,94,.1)" : "rgba(239,68,68,.1)",
              border:`1px solid ${confirmed?"rgba(34,197,94,.25)":"rgba(239,68,68,.25)"}`,
              color: confirmed ? "#22c55e" : "#ef4444" }}>
              {confirmed ? "✓ KRA Confirmed" : "⚠️ Pending Transmission"}
            </span>
          </div>
        </div>

        <div className="et-tabs">
          {[["invoice","Invoice"],["create","New Invoice"],["settings","eTIMS Setup"]].map(([k,l]) => (
            <button key={k} className={`et-tab ${activeTab===k?"active":""}`} onClick={() => setActiveTab(k)}>{l}</button>
          ))}
        </div>

        {activeTab === "invoice" && (
          <>
            <div className="et-receipt">
              <div style={{ textAlign:"center", fontFamily:"'Plus Jakarta Sans',sans-serif" }}>
                <div style={{ fontSize:14, fontWeight:800, color:"var(--t)" }}>ELECTRONIC TAX INVOICE</div>
                <div style={{ fontSize:10, color:"#22c55e", fontWeight:700 }}>Kenya Revenue Authority · eTIMS Certified</div>
              </div>
              <hr className="et-div" />
              <div className="et-r"><span>Seller PIN:</span><span style={{color:"var(--t)"}}>{data.sellerPIN}</span></div>
              <div className="et-r"><span>Seller:</span><span style={{color:"var(--t)"}}>{data.sellerName}</span></div>
              <div className="et-r"><span>Buyer PIN:</span><span style={{color:"var(--t)"}}>{data.buyerPIN}</span></div>
              <div className="et-r"><span>Buyer:</span><span style={{color:"var(--t)"}}>{data.buyerName}</span></div>
              <div className="et-r"><span>Invoice No:</span><span style={{color:BRAND,fontWeight:700}}>{data.invoiceNo}</span></div>
              <div className="et-r"><span>Date/Time:</span><span style={{color:"var(--t)"}}>{data.date} {data.time}</span></div>
              <hr className="et-div" />
              <div className="et-r" style={{fontWeight:700,color:"var(--t)"}}>
                <span>DESCRIPTION</span><span>QTY × PRICE = AMOUNT</span>
              </div>
              {data.items.map((item, i) => (
                <div key={i} className="et-r">
                  <span>{item.desc} {item.vatRate === 0 ? "(Exempt)" : "(VAT 16%)"}</span>
                  <span style={{color:"var(--t)"}}>{item.qty}×{fmt(item.unitPrice,"KSh")}={fmt(item.qty*item.unitPrice,"KSh")}</span>
                </div>
              ))}
              <hr className="et-div" />
              <div className="et-r"><span>Subtotal (excl. VAT):</span><span style={{color:"var(--t)"}}>{fmt(subtotalExVAT,"KSh")}</span></div>
              <div className="et-r"><span>VAT (16%):</span><span style={{color:"#ef4444",fontWeight:700}}>{fmt(vatTotal,"KSh")}</span></div>
              <div className="et-r"><span>VAT-Exempt:</span><span style={{color:"#22c55e"}}>{fmt(exemptItems.reduce((s,i)=>s+i.qty*i.unitPrice,0),"KSh")}</span></div>
              <hr className="et-div" />
              <div className="et-total"><span>GRAND TOTAL:</span><span>{fmt(grandTotal,"KSh")}</span></div>

              {/* QR Code */}
              <div style={{textAlign:"center", marginTop:10}}>
                <div className="et-qr">
                  <div className="et-qr-inner">
                    {QR_PATTERN.map((filled, i) => (
                      <div key={i} className="et-qr-cell"
                        style={{background: filled ? "var(--t)" : "transparent"}} />
                    ))}
                  </div>
                </div>
                <div style={{fontSize:9,color:"var(--t2)"}}>Scan to verify with KRA iTax</div>
                {confirmed && (
                  <div style={{fontSize:9,color:"#22c55e",marginTop:3}}>
                    KRA CONF: {data.kraConfirmCode}
                  </div>
                )}
              </div>
            </div>

            <div style={{display:"flex", gap:8, marginTop:14}}>
              {!confirmed ? (
                <button className="et-btn" style={{flex:1}} onClick={transmit} disabled={sending}>
                  {sending ? "📡 Transmitting to KRA..." : "📡 Submit to KRA eTIMS"}
                </button>
              ) : (
                <button className="et-btn grn" style={{flex:1}}>✓ Verified by KRA</button>
              )}
              <button style={{background:"var(--inp)",border:"1px solid var(--border)",color:"var(--t2)",borderRadius:9,padding:"10px 14px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
                🖨️ Print
              </button>
            </div>
          </>
        )}

        {activeTab === "create" && (
          <>
            <div className="et-r2">
              <div className="et-field"><label className="et-lbl">Buyer KRA PIN</label><input className="et-inp" placeholder="P0XXXXXXXXX" /></div>
              <div className="et-field"><label className="et-lbl">Buyer Name</label><input className="et-inp" placeholder="Business name" /></div>
            </div>
            {[0,1,2].map(i => (
              <div key={i} style={{display:"grid",gridTemplateColumns:"1fr 60px 90px 80px",gap:7,marginBottom:8}}>
                <input className="et-inp" placeholder="Item description" />
                <input className="et-inp" type="number" placeholder="Qty" style={{textAlign:"center"}} />
                <input className="et-inp" type="number" placeholder="KSh price" />
                <select className="et-inp" style={{appearance:"none"}}>
                  <option>VAT 16%</option>
                  <option>Exempt</option>
                  <option>Zero-rated</option>
                </select>
              </div>
            ))}
            <button style={{width:"100%",background:BRAND,color:"#fff",border:"none",borderRadius:9,padding:11,fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:"inherit",marginTop:4}}>
              📡 Create + Submit to KRA
            </button>
          </>
        )}

        {activeTab === "settings" && (
          <div style={{fontSize:11,color:"var(--t2)",lineHeight:1.6}}>
            <div style={{background:"rgba(59,130,246,.06)",border:"1px solid rgba(59,130,246,.2)",borderRadius:10,padding:"11px 13px",marginBottom:12}}>
              <div style={{fontWeight:700,color:"#3b82f6",marginBottom:4}}>KRA eTIMS Certification Required</div>
              Kenya requires 3–6 month KRA system certification before going live. Integration uses
              KRA's Virtual Sales Control Unit (VSCU) API. Apply at itax.kra.go.ke/KRA-Portal/
            </div>
            {[["Seller PIN","P051234567A"],["eTIMS Device ID","VSCU-TZ-001"],["VAT Registration","VAT/123/456/789"],["Invoice Prefix","ETM"]].map(([l,v]) => (
              <div className="et-field" key={l}>
                <label className="et-lbl">{l}</label>
                <input className="et-inp" defaultValue={v} />
              </div>
            ))}
            <button className="et-btn" style={{width:"100%",marginTop:4}}>Save eTIMS Settings</button>
          </div>
        )}
      </div>
    </>
  );
}

// ─── CashbookDashboard ─────────────────────────────────────────────────────────
// Spec C6: "Simplified Bookkeeping Dashboard: Income/expense tracking,
//           profit & loss, balance sheet — Swahili + English"
// This is the daily financial tracking page — standalone, not inside another feature

const CASHBOOK_ENTRIES = [
  { id:1, date:"2025-03-14", desc:"Mauzo ya Jumamosi", descEn:"Saturday sales", type:"income", amount:312800, category:"Sales", method:"mpesa", reconciled:true },
  { id:2, date:"2025-03-14", desc:"Ununuzi wa hisa — Unga", descEn:"Stock purchase — Flour", type:"expense", amount:84000, category:"Stock", method:"cash", reconciled:true },
  { id:3, date:"2025-03-13", desc:"Mauzo ya Ijumaa", descEn:"Friday sales", type:"income", amount:198400, category:"Sales", method:"cash", reconciled:true },
  { id:4, date:"2025-03-13", desc:"Mshahara — Juma na Fatuma", descEn:"Staff salary — Juma & Fatuma", type:"expense", amount:280000, category:"Staff", method:"mpesa", reconciled:true },
  { id:5, date:"2025-03-12", desc:"Mauzo ya Alhamisi", descEn:"Thursday sales", type:"income", amount:172300, category:"Sales", method:"mpesa", reconciled:true },
  { id:6, date:"2025-03-12", desc:"Umeme wa mwezi", descEn:"Monthly electricity", type:"expense", amount:45000, category:"Utilities", method:"mpesa", reconciled:true },
  { id:7, date:"2025-03-11", desc:"Mauzo ya Jumatano", descEn:"Wednesday sales", type:"income", amount:165000, category:"Sales", method:"cash", reconciled:false },
  { id:8, date:"2025-03-11", desc:"Kodi ya duka", descEn:"Shop rent", type:"expense", amount:380000, category:"Rent", reconciled:false },
];

const CATEGORIES = { income:["Sales","Other Income","Loan Received"], expense:["Stock","Staff","Rent","Utilities","Transport","Marketing","Other"] };

export function CashbookDashboard({ theme = "dark" }) {
  const [entries, setEntries] = useState(CASHBOOK_ENTRIES);
  const [lang, setLang] = useState("both");
  const [filter, setFilter] = useState("all");
  const [view, setView] = useState("transactions");
  const [addingEntry, setAddingEntry] = useState(false);
  const [newEntry, setNewEntry] = useState({ desc:"", type:"income", amount:"", category:"Sales", method:"mpesa" });

  const totalIncome  = entries.filter(e => e.type === "income").reduce((s,e) => s+e.amount, 0);
  const totalExpense = entries.filter(e => e.type === "expense").reduce((s,e) => s+e.amount, 0);
  const netProfit    = totalIncome - totalExpense;
  const profitMargin = totalIncome > 0 ? Math.round((netProfit/totalIncome)*100) : 0;

  const filtered = entries.filter(e => filter === "all" || e.type === filter);

  const addEntry = () => {
    if (!newEntry.desc || !newEntry.amount) return;
    setEntries(prev => [{
      id: prev.length + 1,
      date: "2025-03-14",
      desc: newEntry.desc,
      descEn: newEntry.desc,
      type: newEntry.type,
      amount: Number(newEntry.amount),
      category: newEntry.category,
      method: newEntry.method,
      reconciled: false,
    }, ...prev]);
    setAddingEntry(false);
    setNewEntry({ desc:"", type:"income", amount:"", category:"Sales", method:"mpesa" });
  };

  const css2 = `
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');
    .cb-root{font-family:'Plus Jakarta Sans',sans-serif}
    .cb-root.dark{--card:#1a1d27;--inp:#22263a;--border:#2e3347;--t:#f0f2ff;--t2:#7c85a8;--t3:#4a5170}
    .cb-root.light{--card:#fff;--inp:#f8f9fc;--border:#e2e5ef;--t:#1a1d2e;--t2:#5b6380;--t3:#9ba3bf}
    .cb-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:14px}
    @media(max-width:500px){.cb-summary{grid-template-columns:1fr 1fr}}
    .cb-stat{background:var(--card);border:1px solid var(--border);border-radius:11px;padding:11px 13px}
    .cb-stat-l{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--t2);margin-bottom:4px}
    .cb-stat-v{font-size:14px;font-weight:800}
    .cb-tabs{display:flex;gap:3px;background:var(--inp);border-radius:10px;padding:3px;margin-bottom:14px}
    .cb-tab{flex:1;padding:7px;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer;border:none;font-family:inherit;background:transparent;color:var(--t2);transition:all .15s;text-align:center}
    .cb-tab.active{background:${BRAND};color:#fff}
    .cb-row{background:var(--card);border:1px solid var(--border);border-radius:11px;padding:11px 14px;margin-bottom:7px;display:flex;align-items:center;gap:10px}
    .cb-type-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}
    .cb-inp{width:100%;background:var(--inp);border:1.5px solid var(--border);border-radius:8px;padding:8px 11px;font-size:12px;color:var(--t);font-family:inherit;outline:none;transition:border-color .15s;box-sizing:border-box}
    .cb-inp:focus{border-color:${BRAND}}
    .cb-sel{background:var(--inp);border:1.5px solid var(--border);border-radius:8px;padding:8px 11px;font-size:12px;color:var(--t);font-family:inherit;outline:none;appearance:none}
    .cb-add-form{background:var(--card);border:1px solid rgba(229,107,10,.3);border-radius:12px;padding:14px 16px;margin-bottom:12px}
    .cb-progress{height:10px;background:var(--border);border-radius:5px;overflow:hidden;margin:10px 0}
    .cb-progress-fill{height:100%;border-radius:5px;transition:width .4s}
    .lang-tog{display:flex;background:var(--inp);border-radius:7px;overflow:hidden;width:fit-content;margin-bottom:12px}
    .lang-b{padding:4px 12px;font-size:10px;font-weight:700;border:none;cursor:pointer;font-family:inherit;background:transparent;color:var(--t2);transition:all .15s}
    .lang-b.active{background:${BRAND};color:#fff}
  `;

  return (
    <>
      <style>{css2}</style>
      <div className={`cb-root ${theme}`}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}>
          <div>
            <div style={{fontSize:18,fontWeight:800,color:"var(--t)"}}>
              {lang==="sw"?"Daftari la Pesa":"Cashbook"} <span style={{color:BRAND}}>{lang==="sw"?"na Faida":"& P&L"}</span>
            </div>
            <div style={{fontSize:11,color:"var(--t2)",marginTop:2}}>
              {lang==="sw"?"Mapato, matumizi na faida":"Income, expenses and profit"} · March 2025
            </div>
          </div>
          <button onClick={() => setAddingEntry(!addingEntry)}
            style={{background:BRAND,color:"#fff",border:"none",borderRadius:9,padding:"8px 14px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
            + {lang==="sw"?"Ongeza":"Add Entry"}
          </button>
        </div>

        {/* Language toggle */}
        <div className="lang-tog">
          {[["both","SW+EN"],["sw","Swahili"],["en","English"]].map(([k,l]) => (
            <button key={k} className={`lang-b ${lang===k?"active":""}`} onClick={() => setLang(k)}>{l}</button>
          ))}
        </div>

        {/* Summary */}
        <div className="cb-summary">
          {[
            [lang==="sw"?"Mapato":"Income", fmtTZ(totalIncome), "#22c55e"],
            [lang==="sw"?"Matumizi":"Expenses", fmtTZ(totalExpense), "#ef4444"],
            [lang==="sw"?"Faida":"Net Profit", fmtTZ(netProfit), netProfit >= 0 ? "#22c55e" : "#ef4444"],
            [lang==="sw"?"Asilimia ya Faida":"Margin", profitMargin + "%", BRAND],
          ].map(([l,v,c]) => (
            <div className="cb-stat" key={l}>
              <div className="cb-stat-l">{l}</div>
              <div className="cb-stat-v" style={{color:c}}>{v}</div>
            </div>
          ))}
        </div>

        {/* P&L bar */}
        <div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:"13px 16px",marginBottom:14}}>
          <div style={{display:"flex",justifyContent:"space-between",fontSize:11,color:"var(--t2)",marginBottom:4}}>
            <span>{lang==="sw"?"Mapato":"Income"}: {fmtTZ(totalIncome)}</span>
            <span>{lang==="sw"?"Matumizi":"Expenses"}: {fmtTZ(totalExpense)}</span>
          </div>
          <div className="cb-progress">
            <div className="cb-progress-fill" style={{width:`${Math.min(100,Math.round((totalExpense/totalIncome)*100))}%`, background: profitMargin > 30 ? "#22c55e" : profitMargin > 10 ? BRAND : "#ef4444"}} />
          </div>
          <div style={{fontSize:11,color:"var(--t2)",textAlign:"center"}}>
            {lang==="sw" ? `Unafanya faida ya ${profitMargin}% — ` : `${profitMargin}% profit margin — `}
            {profitMargin > 30 ? (lang==="sw"?"Nzuri sana! 🎉":"Excellent! 🎉") : profitMargin > 15 ? (lang==="sw"?"Nzuri":"Good") : (lang==="sw"?"Inaweza kuimarisha":"Can improve")}
          </div>
        </div>

        {/* Tabs */}
        <div className="cb-tabs">
          {[["transactions",lang==="sw"?"Shughuli":"Transactions"],["income",lang==="sw"?"Mapato":"Income"],["expenses",lang==="sw"?"Matumizi":"Expenses"]].map(([k,l]) => (
            <button key={k} className={`cb-tab ${view===k?"active":""}`} onClick={() => { setView(k); setFilter(k==="income"?"income":k==="expenses"?"expense":"all"); }}>
              {l}
            </button>
          ))}
        </div>

        {/* Add entry form */}
        {addingEntry && (
          <div className="cb-add-form">
            <div style={{fontSize:12,fontWeight:700,color:"var(--t)",marginBottom:12}}>
              {lang==="sw"?"Ongeza Shughuli":"Add Transaction"}
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}>
              <select className="cb-sel" value={newEntry.type} onChange={e => setNewEntry(p=>({...p,type:e.target.value,category:e.target.value==="income"?"Sales":"Stock"}))}>
                <option value="income">{lang==="sw"?"Mapato":"Income"}</option>
                <option value="expense">{lang==="sw"?"Matumizi":"Expense"}</option>
              </select>
              <select className="cb-sel" value={newEntry.category} onChange={e => setNewEntry(p=>({...p,category:e.target.value}))}>
                {CATEGORIES[newEntry.type].map(c => <option key={c}>{c}</option>)}
              </select>
            </div>
            <input className="cb-inp" style={{marginBottom:8}} placeholder={lang==="sw"?"Maelezo / Description":"Description"} value={newEntry.desc} onChange={e => setNewEntry(p=>({...p,desc:e.target.value}))} />
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:10}}>
              <input className="cb-inp" type="number" placeholder="Amount (TSh)" value={newEntry.amount} onChange={e => setNewEntry(p=>({...p,amount:e.target.value}))} />
              <select className="cb-sel" value={newEntry.method} onChange={e => setNewEntry(p=>({...p,method:e.target.value}))}>
                <option value="mpesa">M-Pesa</option>
                <option value="cash">Cash</option>
                <option value="airtel">Airtel Money</option>
              </select>
            </div>
            <div style={{display:"flex",gap:8}}>
              <button onClick={addEntry} style={{flex:1,background:BRAND,color:"#fff",border:"none",borderRadius:8,padding:9,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
                ✓ {lang==="sw"?"Hifadhi":"Save"}
              </button>
              <button onClick={() => setAddingEntry(false)} style={{background:"var(--inp)",border:"1px solid var(--border)",color:"var(--t2)",borderRadius:8,padding:9,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
                {lang==="sw"?"Ghairi":"Cancel"}
              </button>
            </div>
          </div>
        )}

        {/* Entry list */}
        {filtered.map(entry => (
          <div key={entry.id} className="cb-row">
            <div className="cb-type-dot" style={{background: entry.type==="income"?"#22c55e":"#ef4444"}} />
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontSize:12,fontWeight:700,color:"var(--t)",display:"flex",alignItems:"center",gap:6}}>
                {lang==="sw" ? entry.desc : lang==="en" ? entry.descEn : entry.descEn}
                {!entry.reconciled && <span style={{fontSize:9,color:"#f59e0b",fontWeight:700}}>⚠️ Unverified</span>}
              </div>
              <div style={{fontSize:10,color:"var(--t2)",marginTop:1}}>
                {entry.date} · {entry.category} · {entry.method.toUpperCase()}
                {lang==="both" && entry.desc !== entry.descEn && <span style={{fontStyle:"italic"}}> — {entry.desc}</span>}
              </div>
            </div>
            <div style={{textAlign:"right",flexShrink:0}}>
              <div style={{fontSize:13,fontWeight:800,color:entry.type==="income"?"#22c55e":"#ef4444"}}>
                {entry.type==="income"?"+":"-"}{fmtTZ(entry.amount)}
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}

// ─── PDPAConsentManager ───────────────────────────────────────────────────────
// Spec E: "Personal Data Protection Act (PDPA) 2022 — effective May 2023.
//          Register with PDPC; appoint DPO; quarterly reports"
// Required for any data collected from merchants and their customers

export function PDPAConsentManager({ theme = "dark", userType = "merchant" }) {
  const [consents, setConsents] = useState({
    core: true,
    analytics: false,
    marketing: false,
    thirdParty: false,
    creditBureau: false,
  });
  const [dpoAppointed, setDpoAppointed] = useState(false);
  const [pdpcRegistered, setPdpcRegistered] = useState(false);
  const [view, setView] = useState("merchant");

  const toggle = (key) => setConsents(prev => ({...prev, [key]: !prev[key]}));

  const css3 = `
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');
    .pdpa-root{font-family:'Plus Jakarta Sans',sans-serif}
    .pdpa-root.dark{--card:#1a1d27;--inp:#22263a;--border:#2e3347;--t:#f0f2ff;--t2:#7c85a8;--t3:#4a5170}
    .pdpa-root.light{--card:#fff;--inp:#f8f9fc;--border:#e2e5ef;--t:#1a1d2e;--t2:#5b6380;--t3:#9ba3bf}
    .pdpa-card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:14px 16px;margin-bottom:10px}
    .pdpa-consent-row{display:flex;align-items:flex-start;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border)}
    .pdpa-consent-row:last-child{border-bottom:none}
    .pdpa-toggle{width:40px;height:22px;border-radius:11px;position:relative;cursor:pointer;flex-shrink:0;transition:background .2s;border:none}
    .pdpa-toggle-thumb{position:absolute;top:2px;width:18px;height:18px;border-radius:50%;background:#fff;transition:left .2s}
    .pdpa-lbl{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.7px;color:${BRAND};margin-bottom:8px}
  `;

  const CONSENTS_CONFIG = [
    { key:"core", label:"Core App Functionality", labelSw:"Utendaji wa Msingi wa Programu", required:true, desc:"Transaction recording, inventory, invoicing — required to use the app." },
    { key:"analytics", label:"Usage Analytics", labelSw:"Uchanganuzi wa Matumizi", required:false, desc:"Anonymous usage data to improve the product (no financial data shared)." },
    { key:"marketing", label:"Marketing Communications", labelSw:"Mawasiliano ya Masoko", required:false, desc:"Product updates, tips, and new feature announcements via SMS/Email." },
    { key:"thirdParty", label:"Third-Party Integrations", labelSw:"Ushirikiano wa Wahusika Wengine", required:false, desc:"Share data with ClickPesa, Africa's Talking for payment processing and SMS." },
    { key:"creditBureau", label:"Credit Bureau Reporting", labelSw:"Ripoti ya Biro ya Mkopo", required:false, desc:"Share transaction history with credit bureaus to build your credit score." },
  ];

  return (
    <>
      <style>{css3}</style>
      <div className={`pdpa-root ${theme}`}>
        <div style={{marginBottom:14}}>
          <div style={{fontSize:18,fontWeight:800,color:"var(--t)"}}>
            PDPA <span style={{color:BRAND}}>Data Privacy</span>
          </div>
          <div style={{fontSize:11,color:"var(--t2)",marginTop:2}}>
            Tanzania Personal Data Protection Act 2022 · Effective May 2023
          </div>
        </div>

        {/* Merchant consent panel */}
        <div className="pdpa-card">
          <div className="pdpa-lbl">Your Data Consent (Idhini ya Data Yako)</div>
          {CONSENTS_CONFIG.map(c => (
            <div key={c.key} className="pdpa-consent-row">
              <div style={{flex:1,marginRight:14}}>
                <div style={{fontSize:12,fontWeight:700,color:"var(--t)",display:"flex",alignItems:"center",gap:6}}>
                  {c.label}
                  {c.required && <span style={{fontSize:9,background:"rgba(229,107,10,.1)",color:BRAND,border:"1px solid rgba(229,107,10,.2)",borderRadius:20,padding:"1px 7px",fontWeight:700}}>Required</span>}
                </div>
                <div style={{fontSize:10,color:"var(--t2)",marginTop:2,fontStyle:"italic"}}>{c.labelSw}</div>
                <div style={{fontSize:10,color:"var(--t2)",marginTop:3,lineHeight:1.4}}>{c.desc}</div>
              </div>
              <button
                className="pdpa-toggle"
                style={{background: c.required || consents[c.key] ? "#22c55e" : "var(--border)"}}
                disabled={c.required}
                onClick={() => !c.required && toggle(c.key)}>
                <div className="pdpa-toggle-thumb"
                  style={{left: c.required || consents[c.key] ? "20px" : "2px"}} />
              </button>
            </div>
          ))}
        </div>

        {/* CREOVA compliance status */}
        <div className="pdpa-card">
          <div className="pdpa-lbl">CREOVA PDPA Compliance Status</div>
          {[
            { label:"PDPC Registration", desc:"Registered with Data Protection Commission", done:pdpcRegistered, action:() => setPdpcRegistered(true), actionLabel:"Register" },
            { label:"DPO Appointed", desc:"Data Protection Officer assigned", done:dpoAppointed, action:() => setDpoAppointed(true), actionLabel:"Appoint DPO" },
            { label:"Privacy Policy Published", desc:"Accessible in-app and on website", done:true, action:null, actionLabel:null },
            { label:"Data Breach Procedure", desc:"72-hour notification protocol documented", done:true, action:null, actionLabel:null },
            { label:"Quarterly PDPC Report", desc:"Next due: June 30, 2025", done:false, action:null, actionLabel:"Prepare Report" },
          ].map(item => (
            <div key={item.label} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"9px 0",borderBottom:"1px solid var(--border)"}}>
              <div>
                <div style={{fontSize:12,fontWeight:700,color:"var(--t)"}}>{item.label}</div>
                <div style={{fontSize:10,color:"var(--t2)",marginTop:1}}>{item.desc}</div>
              </div>
              <div style={{display:"flex",alignItems:"center",gap:8,flexShrink:0}}>
                <span style={{fontSize:10,fontWeight:700,color:item.done?"#22c55e":"#f59e0b"}}>{item.done?"✓":"Pending"}</span>
                {!item.done && item.actionLabel && (
                  <button onClick={item.action} style={{background:"var(--inp)",border:"1px solid var(--border)",color:"var(--t2)",borderRadius:7,padding:"4px 9px",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
                    {item.actionLabel}
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>

        <div style={{background:"rgba(59,130,246,.06)",border:"1px solid rgba(59,130,246,.2)",borderRadius:10,padding:"11px 13px",fontSize:11,color:"var(--t2)",lineHeight:1.5}}>
          💡 Under Tanzania PDPA 2022, data controllers must register with the PDPC, appoint a DPO,
          submit quarterly compliance reports, and notify the PDPC of data breaches within 72 hours.
          Non-compliance: fines up to TZS 50M.
        </div>
      </div>
    </>
  );
}

// ─── TANQRDisplay ─────────────────────────────────────────────────────────────
// Spec: BoT TAN-QR — national QR code payment standard mandated by Bank of Tanzania
// All merchants accepting digital payments must display TAN-QR at POS
// Customers scan with any bank/MNO app to pay — interoperable across all providers

export function TANQRDisplay({ 
  merchantName = "Duka la Mwanga",
  businessTill = "TANQR-8821-0047",
  tin = "123-456-789-T",
  amount = null, // null = open amount (customer enters), number = fixed amount
  theme = "dark"
}) {
  const [customAmount, setCustomAmount] = useState(amount ? String(amount) : "");
  const [generated, setGenerated] = useState(!!amount);

  const QR = Array.from({length:100}, (_,i) => {
    const r = Math.floor(i/10), c = i%10;
    return r < 2 || c < 2 || r > 7 || c > 7 ||
      (r === 3 && c > 2 && c < 8) || (r === 5 && c > 1 && c < 7) ||
      (r%2 === 0 && c%3 === 0) || (r*c) % 7 === 0;
  });

  const css4 = `
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap');
    .qr-root{font-family:'Plus Jakarta Sans',sans-serif}
    .qr-root.dark{--card:#1a1d27;--inp:#22263a;--border:#2e3347;--t:#f0f2ff;--t2:#7c85a8}
    .qr-root.light{--card:#fff;--inp:#f8f9fc;--border:#e2e5ef;--t:#1a1d2e;--t2:#5b6380}
    .qr-card{background:var(--card);border:2px solid rgba(229,107,10,.3);border-radius:16px;padding:20px;text-align:center;max-width:280px;margin:0 auto}
    .qr-grid{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;width:140px;height:140px;margin:12px auto}
    .qr-cell{border-radius:2px}
    .qr-inp{background:var(--inp);border:1.5px solid var(--border);border-radius:9px;padding:10px;font-size:16px;color:var(--t);font-family:'IBM Plex Mono',monospace;outline:none;width:100%;box-sizing:border-box;text-align:center;transition:border-color .15s;font-weight:700}
    .qr-inp:focus{border-color:${BRAND}}
  `;

  return (
    <>
      <style>{css4}</style>
      <div className={`qr-root ${theme}`}>
        <div style={{marginBottom:14}}>
          <div style={{fontSize:18,fontWeight:800,color:"var(--t)"}}>
            TAN-QR <span style={{color:BRAND}}>Payment</span>
          </div>
          <div style={{fontSize:11,color:"var(--t2)",marginTop:2}}>
            Bank of Tanzania national QR standard · Works with all MNOs & banks
          </div>
        </div>

        <div className="qr-card">
          <div style={{fontSize:10,fontWeight:700,color:"rgba(229,107,10,.7)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:4}}>TAN-QR · Lipa Hapa</div>
          <div style={{fontSize:16,fontWeight:800,color:"var(--t)"}}>{merchantName}</div>
          <div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:10,color:"var(--t2)",marginTop:2}}>{businessTill}</div>

          {(generated || amount) ? (
            <>
              <div className="qr-grid">
                {QR.map((filled, i) => (
                  <div key={i} className="qr-cell"
                    style={{background: filled ? "var(--t)" : "transparent"}} />
                ))}
              </div>
              {customAmount && (
                <div style={{fontSize:20,fontWeight:800,color:BRAND,margin:"8px 0"}}>{fmtTZ(Number(customAmount))}</div>
              )}
              <div style={{fontSize:10,color:"var(--t2)",marginTop:4}}>
                Scan with M-Pesa, Airtel, Tigo, HaloPesa, CRDB, or any bank app
              </div>
            </>
          ) : (
            <>
              <div style={{margin:"14px 0 8px",fontSize:12,color:"var(--t2)"}}>
                Ingiza kiasi / Enter amount:
              </div>
              <input className="qr-inp"
                type="number"
                placeholder="0"
                value={customAmount}
                onChange={e => setCustomAmount(e.target.value)} />
              <button
                style={{width:"100%",background:BRAND,color:"#fff",border:"none",borderRadius:9,padding:10,fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:"inherit",marginTop:10}}
                onClick={() => setGenerated(true)}>
                Generate QR Code
              </button>
            </>
          )}

          {(generated || amount) && (
            <div style={{display:"flex",gap:6,marginTop:12}}>
              <button style={{flex:1,background:"var(--inp)",border:"1px solid var(--border)",color:"var(--t2)",borderRadius:8,padding:8,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}
                onClick={() => {setGenerated(false);setCustomAmount("");}}>
                New Amount
              </button>
              <button style={{flex:1,background:"rgba(34,197,94,.1)",border:"1px solid rgba(34,197,94,.25)",color:"#22c55e",borderRadius:8,padding:8,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>
                Share QR
              </button>
            </div>
          )}
        </div>

        <div style={{marginTop:14,background:"rgba(59,130,246,.06)",border:"1px solid rgba(59,130,246,.2)",borderRadius:10,padding:"11px 13px",fontSize:11,color:"var(--t2)",lineHeight:1.5}}>
          💡 TAN-QR is the Bank of Tanzania's national interoperable QR standard. One QR code works
          across all mobile money providers and banks — customers can pay from any app.
        </div>
      </div>
    </>
  );
}
